// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: Dummy.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dummy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Dummy) Reset() {
	*x = Dummy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Dummy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dummy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dummy) ProtoMessage() {}

func (x *Dummy) ProtoReflect() protoreflect.Message {
	mi := &file_Dummy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dummy.ProtoReflect.Descriptor instead.
func (*Dummy) Descriptor() ([]byte, []int) {
	return file_Dummy_proto_rawDescGZIP(), []int{0}
}

func (x *Dummy) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_Dummy_proto protoreflect.FileDescriptor

var file_Dummy_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x42, 0x18, 0x0a,
	0x09, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x6a, 0x61, 0x76, 0x61, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x62,
	0x2f, 0x67, 0x6f, 0x3b, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Dummy_proto_rawDescOnce sync.Once
	file_Dummy_proto_rawDescData = file_Dummy_proto_rawDesc
)

func file_Dummy_proto_rawDescGZIP() []byte {
	file_Dummy_proto_rawDescOnce.Do(func() {
		file_Dummy_proto_rawDescData = protoimpl.X.CompressGZIP(file_Dummy_proto_rawDescData)
	})
	return file_Dummy_proto_rawDescData
}

var file_Dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Dummy_proto_goTypes = []interface{}{
	(*Dummy)(nil), // 0: proto.Dummy
}
var file_Dummy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Dummy_proto_init() }
func file_Dummy_proto_init() {
	if File_Dummy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Dummy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dummy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Dummy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Dummy_proto_goTypes,
		DependencyIndexes: file_Dummy_proto_depIdxs,
		MessageInfos:      file_Dummy_proto_msgTypes,
	}.Build()
	File_Dummy_proto = out.File
	file_Dummy_proto_rawDesc = nil
	file_Dummy_proto_goTypes = nil
	file_Dummy_proto_depIdxs = nil
}
