// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: ProtoBuf_Intro.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EyeColor int32

const (
	// Remember enum range start from 0... unlike tags(it's from 1)
	EyeColor_EYE_COLOR_UNSPECIFIED EyeColor = 0
	EyeColor_EYE_COLOR_BLACK       EyeColor = 1
	EyeColor_EYE_COLOR_BLUE        EyeColor = 2
)

// Enum value maps for EyeColor.
var (
	EyeColor_name = map[int32]string{
		0: "EYE_COLOR_UNSPECIFIED",
		1: "EYE_COLOR_BLACK",
		2: "EYE_COLOR_BLUE",
	}
	EyeColor_value = map[string]int32{
		"EYE_COLOR_UNSPECIFIED": 0,
		"EYE_COLOR_BLACK":       1,
		"EYE_COLOR_BLUE":        2,
	}
)

func (x EyeColor) Enum() *EyeColor {
	p := new(EyeColor)
	*p = x
	return p
}

func (x EyeColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EyeColor) Descriptor() protoreflect.EnumDescriptor {
	return file_ProtoBuf_Intro_proto_enumTypes[0].Descriptor()
}

func (EyeColor) Type() protoreflect.EnumType {
	return &file_ProtoBuf_Intro_proto_enumTypes[0]
}

func (x EyeColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EyeColor.Descriptor instead.
func (EyeColor) EnumDescriptor() ([]byte, []int) {
	return file_ProtoBuf_Intro_proto_rawDescGZIP(), []int{0}
}

//*
//Account:
//Used for storing data of person.
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Thumbnail  []byte  `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	IsVarified bool    `protobuf:"varint,4,opt,name=isVarified,proto3" json:"isVarified,omitempty"`
	Height     float32 `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	// For list we can use repeated
	Phones []string `protobuf:"bytes,6,rep,name=phones,proto3" json:"phones,omitempty"`
	// Enums
	EyeColor EyeColor `protobuf:"varint,7,opt,name=eyeColor,proto3,enum=proto.EyeColor" json:"eyeColor,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoBuf_Intro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoBuf_Intro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_ProtoBuf_Intro_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *Account) GetIsVarified() bool {
	if x != nil {
		return x.IsVarified
	}
	return false
}

func (x *Account) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Account) GetPhones() []string {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *Account) GetEyeColor() EyeColor {
	if x != nil {
		return x.EyeColor
	}
	return EyeColor_EYE_COLOR_UNSPECIFIED
}

var File_ProtoBuf_Intro_proto protoreflect.FileDescriptor

var file_ProtoBuf_Intro_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x5f, 0x49, 0x6e, 0x74, 0x72, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x73, 0x56, 0x61, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x69, 0x73, 0x56, 0x61, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x65,
	0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08,
	0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x4e, 0x0a, 0x08, 0x45, 0x79, 0x65, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f,
	0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x41,
	0x43, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x59, 0x45, 0x5f, 0x43, 0x4f, 0x4c, 0x4f,
	0x52, 0x5f, 0x42, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x42, 0x18, 0x0a, 0x09, 0x2e, 0x2f, 0x70, 0x62,
	0x2f, 0x6a, 0x61, 0x76, 0x61, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x3b, 0x67,
	0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ProtoBuf_Intro_proto_rawDescOnce sync.Once
	file_ProtoBuf_Intro_proto_rawDescData = file_ProtoBuf_Intro_proto_rawDesc
)

func file_ProtoBuf_Intro_proto_rawDescGZIP() []byte {
	file_ProtoBuf_Intro_proto_rawDescOnce.Do(func() {
		file_ProtoBuf_Intro_proto_rawDescData = protoimpl.X.CompressGZIP(file_ProtoBuf_Intro_proto_rawDescData)
	})
	return file_ProtoBuf_Intro_proto_rawDescData
}

var file_ProtoBuf_Intro_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ProtoBuf_Intro_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ProtoBuf_Intro_proto_goTypes = []interface{}{
	(EyeColor)(0),   // 0: proto.EyeColor
	(*Account)(nil), // 1: proto.Account
}
var file_ProtoBuf_Intro_proto_depIdxs = []int32{
	0, // 0: proto.Account.eyeColor:type_name -> proto.EyeColor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ProtoBuf_Intro_proto_init() }
func file_ProtoBuf_Intro_proto_init() {
	if File_ProtoBuf_Intro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ProtoBuf_Intro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ProtoBuf_Intro_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProtoBuf_Intro_proto_goTypes,
		DependencyIndexes: file_ProtoBuf_Intro_proto_depIdxs,
		EnumInfos:         file_ProtoBuf_Intro_proto_enumTypes,
		MessageInfos:      file_ProtoBuf_Intro_proto_msgTypes,
	}.Build()
	File_ProtoBuf_Intro_proto = out.File
	file_ProtoBuf_Intro_proto_rawDesc = nil
	file_ProtoBuf_Intro_proto_goTypes = nil
	file_ProtoBuf_Intro_proto_depIdxs = nil
}
